# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'airapps' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for airapps
  pod 'React', :path => '../js/node_modules/react-native', :subspecs => [
    'Core',
    'ART',
    'RCTActionSheet',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
  pod 'WeChatSDK'
  target 'airappsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
